### ISSUE TITLE
Fix postrges on macos self-hosted runner

### ISSUE THREAD

**Issue by kuvaldini** [hyperledger/iroha#1356]
Build failed on self hosted macos runner because of problem with postgres

https://github.com/hyperledger/iroha/pull/1355/checks?check_run_id=3393007196

Solution looks like here https://serverfault.com/questions/10226/how-to-set-the-shmmax-parameter-on-mac-os-x

**Comment by kuvaldini** [comment]
@ryjones Helly, Ry could you try to fix our rare but persistant problem with testing (i.e. running postgresql) on our self-hosted Mac.
I've never met such a problem on other runners.

**Comment by ryjones** [comment]
done

**Comment by ryjones** [comment]
@kuvaldini it looks like you aren't filtering for [push, pr] in GHA, which doubles your run time

**Comment by kuvaldini** [comment]
@ryjones, yes branches main, support/* and gha-* runs twice when pushed and on pr-sync event. They build the same but behaves slightly different. For example, PRs from forks cannot publish to GHCR and DockerHub, but branches can. We use docker images for testing. Branches with gha- are previliged :) just for testing purposes.
Did I understand your remark right?

**Comment by kuvaldini** [comment]
> done

Unfortunately this did not help still the same error on fresh workflow run. https://github.com/hyperledger/iroha/runs/3394595611?check_suite_focus=true

**Comment by ryjones** [comment]
I used another method and the test made it past that point.

**Comment by ryjones** [comment]
I think the cache size needs adjusted, since it is just over the limit. Also, I think requiring self-hosted for Mac builds would speed everything, since there will be caching.

**Comment by kuvaldini** [comment]
Yes. Next our step is to disable non self hosted runners.

**Comment by kuvaldini** [comment]
Thank you. Today the problem did not appear.

**Comment by ryjones** [comment]
ok.
